
export enum ToolType {
  // CORE
  ARTICLE_REWRITER = 'ARTICLE_REWRITER',
  GRAMMAR_FIXER = 'GRAMMAR_FIXER',
  PARAPHRASER = 'PARAPHRASER',
  TITLE_GENERATOR = 'TITLE_GENERATOR',
  META_DESCRIPTION = 'META_DESCRIPTION',
  
  // CONTENT CREATION
  BLOG_OUTLINE = 'BLOG_OUTLINE',
  INTRO_GEN = 'INTRO_GEN',
  CONCLUSION_GEN = 'CONCLUSION_GEN',
  FAQ_GEN = 'FAQ_GEN',
  EXPANDER = 'EXPANDER',
  SHORTENER = 'SHORTENER',
  TONE_CHANGER = 'TONE_CHANGER',
  LONG_FORM_GEN = 'LONG_FORM_GEN',

  // SEO & OPTIMIZATION
  KEYWORD_IDEAS = 'KEYWORD_IDEAS',
  SEO_OPTIMIZER = 'SEO_OPTIMIZER',
  HEADING_GEN = 'HEADING_GEN',
  SLUG_GEN = 'SLUG_GEN',
  SNIPPET_GEN = 'SNIPPET_GEN',
  PAA_GEN = 'PAA_GEN',
  CONTENT_GAP_ANALYZER = 'CONTENT_GAP_ANALYZER',
  COMPETITOR_ANALYZER = 'COMPETITOR_ANALYZER',

  // REWRITING & HUMANIZING
  SENTENCE_REWRITER = 'SENTENCE_REWRITER',
  PARAGRAPH_REWRITER = 'PARAGRAPH_REWRITER',
  PLAGIARISM_SAFE = 'PLAGIARISM_SAFE',
  ACTIVE_PASSIVE = 'ACTIVE_PASSIVE',
  PASSIVE_ACTIVE = 'PASSIVE_ACTIVE',
  AI_HUMANIZER = 'AI_HUMANIZER',

  // MARKETING & COPYWRITING
  AD_COPY = 'AD_COPY',
  CTA_GEN = 'CTA_GEN',
  EMAIL_SUBJECT = 'EMAIL_SUBJECT',
  PRODUCT_DESC = 'PRODUCT_DESC',
  LANDING_PAGE = 'LANDING_PAGE',
  CONTENT_REPURPOSER = 'CONTENT_REPURPOSER',

  // SOCIAL MEDIA
  SOCIAL_CAPTION = 'SOCIAL_CAPTION',
  HASHTAG_GEN = 'HASHTAG_GEN',
  YT_TITLE = 'YT_TITLE',
  YT_DESC = 'YT_DESC',
  YT_TAGS = 'YT_TAGS',

  // UTILITIES
  READABILITY_IMPROVER = 'READABILITY_IMPROVER',
  SIMPLIFIER = 'SIMPLIFIER',
  KEYWORD_DENSITY = 'KEYWORD_DENSITY',
  SEO_CHECKLIST = 'SEO_CHECKLIST'
}

export enum WritingMode {
  DEFAULT = 'DEFAULT',
  SEO = 'SEO',
  SIMPLE = 'SIMPLE',
  PROFESSIONAL = 'PROFESSIONAL'
}

export interface ToolConfig {
  id: ToolType;
  name: string;
  description: string;
  icon: string;
  placeholder: string;
  buttonText: string;
}

export interface ToolCategory {
  name: string;
  tools: ToolType[];
}

export interface GenerationResult {
  content: string;
  error?: string;
}
